repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.89.1
    hooks:
      - id: terraform_fmt
        files: ^terraform/
      - id: terraform_docs
        files: ^terraform/
        args:
          - '--args=--lockfile=false'
      - id: terraform_tflint
        files: ^terraform/
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'
          - '--args=--only=terraform_unused_required_providers'
      - id: terraform_validate
        files: ^terraform/

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: bash -c "cargo fmt -- --check"
        language: system
        types: [rust]

      - id: cargo-clippy
        name: cargo clippy
        entry: bash -c "cargo clippy --all-targets --all-features -- -D warnings"
        language: system
        types: [rust]

      - id: cargo-test
        name: cargo test
        entry: bash -c "cargo test --all-targets --all-features"
        language: system
        types: [rust]
