apiVersion: v1
kind: Service
metadata:
  name: rust-service
  namespace: rust-services
spec:
  selector:
    app: rust-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
