name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  
        token: ${{ secrets.TOKEN }} 


    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose


  rustfmt:
    name: Check and Fix Rust Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          token: ${{ secrets.TOKEN }}  
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable


  audit-dependencies:
    name: Audit Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          token: ${{ secrets.TOKEN }} 
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-audit
        run: cargo install cargo-audit
      - name: Run Dependency Audit
        run: cargo audit

  lint:
    name: Rust Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          token: ${{ secrets.TOKEN }} 
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install Clippy
        run: rustup component add clippy
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
